object Visual {
    //Funciones a la cual hay texto o arte ascii
    fun presentation(player: PlayerStats) {
        println("    ////////  ========================")
        println(" .  =======   =Como quieres llamarte?=")
        println("( )| O   O |  /=======================")
        println(" # | ____  | / ")
        println(" #   _| |_")
        println(" #  (     )")
        println("(#)==|   |")
        println(" #   |   |  ")
        println(" #   =====  ")
        println(" #   (   ) ")
        println(" #   || ||")
        println(".#---'| |`----.")
        println("`#----' `-----'")

        val name1 = readLine()
        if (name1 != null) {
            player.name = name1
        }
        MapFun.clearScreen()
        println("   \\\\\\\\\\\\\\\\  ")
        println(" .  =======    Tu nombre es: \u001B[33;1m${player.name}\u001B[0m!")
        println("( )| O   O |  /")
        println(" # | ____  | / ")
        println(" #   _| |_")
        println(" #  (     )")
        println("(#)==|   |")
        println(" #   |   |  ")
        println(" #   =====  ")
        println(" #   (   ) ")
        println(" #   || ||")
        println(".#---'| |`----.")
        println("`#----' `-----'")
        Thread.sleep(2000)
        MapFun.clearScreen()
        println("    ////////   =====================================")
        println(" .  =======    =Por cierto, te pondre una \u001B[31mmaldición\u001B[0m=")
        println("( )| O   O |  /=====================================")
        println(" # | ____  | / ")
        println(" #   _| |_")
        println(" #  (     )")
        println("(#)==|   |")
        println(" #   |   |  ")
        println(" #   =====  ")
        println(" #   (   ) ")
        println(" #   || ||")
        println(".#---'| |`----.")
        println("`#----' `-----'")
        Thread.sleep(2000)
        MapFun.clearScreen()
        println("   \\\\\\\\\\\\\\\\   ==========================================")
        println(" .  =======   =Este es el mapa, si no entiendes nada   =")
        println("( )| O   O |  =o lo que tienes que hacer, escribe \u001B[33;1mhelp\u001B[0m =")
        println(" # | ____  | /==========================================")
        println(" #   _| |_")
        println(" #  (     )")
        println("(#)==|   |")
        println(" #   |   |  ")
        println(" #   =====  ")
        println(" #   (   ) ")
        println(" #   || ||")
        println(".#---'| |`----.")
        println("`#----' `-----'")
        MapFun.printMap()
    }

    fun showHelp() {
        println("Los controles son:")
        println("\n- w- ->arriba")
        println("- d -->derecha")
        println("- s -->abajo")
        println("- a -->izquierda")
        println("- use sword/potion/boomb/gun")
        println("- inventory/help")
        println("\nDatos general:")
        println("Las letras significan algo, si quieres saber lo que significa, descubrelo por tu parte.")
        println("El '@' significa donde estas tu, si escribes un comando erroneo, en el mapa no se te marcara")
        println("Si te encuentras en un obejto pero no lo pillas, desaparecera, porque tienes una \u001B[31mmaldición\u001B[0m")
        println("El # es el borde del mapa, y la D es una puerta a la cual has de ir escribiendo use key para abrir la puerta")
        MapFun.printMap()
    }

    fun asciiPotion() {
        println("hay una pocion en el suelo, quieres pillarlo? (yes/no)")
        println()
        println("\u001b[31m  |    | \u001b[0m")
        println("\u001b[31m C|====| \u001b[0m")
        println("\u001b[31m  |  º | \u001b[0m")
        println("\u001b[31m  '----' \u001b[0m")
        println()
    }

    fun asciiBomb() {
        println("hay una bomba en el suelo, quieres pillarlo? (yes/no)")
        println()
        println("\u001B[30m        ,--.!,")
        println("     __/   -*-")
        println("   ,d08b.  '|`")
        println("   0088MM")
        println("   `9MMP'\u001B[0m")
        println()
    }

    fun asciiSword() {
        println("hay una espada en el suelo, quieres pillarlo? (yes/no)")
        println()
        //+=={:::::::::::::::::> otra espada si no gusta
        println("\u001B[33;1m      .\u001B[0m \u001B[37;1m ________________\u001B[0m")
        println("\u001B[33;1mO|===| |\u001B[0m \u001B[37;1m________________>\u001B[0m")
        println("\u001B[33;1m      ·\u001B[0m")
        println()
    }

    fun asciiGun() {
        println("hay una pistola en el suelo, quieres pillarlo? (yes/no)")
        println("\u001B[30m   +--^----------,--------,-----,--------^-,")
        println("   | |||||||||   `--------'     |          O")
        println("   `+---------------------------^----------|")
        println("     `\\_,---------,---------,--------------'")
        println("       / XXXXXX /'|       /'")
        println("      / XXXXXX /  `\\    /'")
        println("     / XXXXXX /`-------'")
        println("    / XXXXXX /")
        println("   / XXXXXX /")
        println("  (________(")
        println("   `------'\u001B[0m")
    }

    fun asciiKey() {
        println("hay una llave en el suelo, quieres pillarlo? (yes/no)")
        println("Este es el unico objeto que si dices que no, puede que sea imposible acabar el juego, elige bien")
        println()
        println("\u001B[33;1m  8 8          ,o.   \u001B[0m")
        println("\u001B[33;1m d8o8azzzzzzzzd   b\u001B[0m")
        println("\u001B[33;1m               `o'\u001B[0m")
        println()
    }

    fun asciiGoblin() {
        println("\u001B[32m    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣶⣿⣿⣶⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⣿⣿⣿⣿⣿⣿⣿⣷⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠀⢀⡼⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⢧⡀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠢⣤⣀⡀⠀⠀⠀⢿⣧⣄⡉⠻⢿⣿⣿⡿⠟⢉⣠⣼⡿⠀⠀⠀⠀⣀⣤⠔⠀")
        println("  ⠀⠀⠈⢻⣿⣶⠀⣷⠀⠉⠛⠿⠶⡴⢿⡿⢦⠶⠿⠛⠉⠀⣾⠀⣶⣿⡟⠁⠀⠀")
        println("  ⠀⠀⠀⠀⠻⣿⡆⠘⡇⠘⠷⠠⠦⠀⣾⣷⠀⠴⠄⠾⠃⢸⠃⢰⣿⠟⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀⠋⢠⣾⣥⣴⣶⣶⣆⠘⣿⣿⠃⣰⣶⣶⣦⣬⣷⡄⠙⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⢋⠛⠻⠿⣿⠟⢹⣆⠸⠇⣰⡏⠻⣿⠿⠟⠛⡙⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠈⢧⡀⠠⠄⠀⠈⠛⠀⠀⠛⠁⠀⠠⠄⢀⡼⠁⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠈⢻⣦⡀⠃⠀⣿⡆⢰⣿⠀⠘⢀⣴⡟⠁⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⣿⣦⡀⠘⠇⠸⠃⢀⣴⣿⠏⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣿⣷⣄⣠⣾⣿⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⣿⣿⠟⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀\u001B[0m")
    }

    fun asciiTroll() {

        println("\u001B[32m   ⠀⠀⠀⠀⠀⠀⠀  ⠀⠀⠀⠀⠀⠀⣀⣀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀ ⠀⠀⠀⢀⣠⣤⣶⡾⠛⠉⠁⠀⠀⠈⠉⠻⢿⣶⣶⣤⣀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀ ⠀⣿⣿⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⣿⣿⣿⠀⠀⣀⠀⠀⠀")
        println("   ⠀⢀⣴⣇⠀⠀⣿⡟⢁⠀⣠⠀⠀⣀⠀⠀⡀⠀⢠⣀⠀⠈⢿⡟⠀⠀⣿⣷⣄⠀")
        println("   ⠀⣿⣏⠙⠀⠀⠿⠃⣼⣾⣿⣤⣾⣿⣆⣼⣿⣦⣸⣿⣷⣇⠸⡇⠀⠀⠛⢻⣿⠀")
        println("   ⠀⣿⣿⣦⠙⣶⣶⣤⣿⣿⡛⣉⣉⡙⠻⣿⡿⠋⣉⣉⠻⣿⣠⣤⣶⠖⣰⣿⣿⠀")
        println("   ⠀⣿⣿⣿⡀⠈⠻⣿⣿⣿⣿⣭⣽⡏⢰⣿⠀⣿⣭⣽⣿⣿⣿⡿⠃⢸⣿⣿⣿⠀")
        println("   ⠀⣿⣿⣿⡇⠀⢠⣬⡉⢿⣿⣿⡿⢀⣿⣿⣆⠸⣿⣿⡿⢋⣩⠀⠀⢸⣿⣿⣿⠀")
        println("   ⠀⣿⣿⣿⡇⠀⠀⣿⣿⣄⠻⢿⠃⣼⣿⣿⣿⡄⠻⠋⣠⣿⣿⠀⠀⣿⣿⣿⣿⠀")
        println("   ⠀⣿⣿⣿⣇⠀⠀⣿⣿⣿⣷⡆⢠⣿⣿⣿⣿⣿⠀⣿⣿⣿⡏⠀⠀⣿⣿⣿⣿⠀")
        println("   ⠀⣿⣿⣿⣿⠀⠀⣿⣿⣿⣿⣷⣌⠛⠛⠛⠛⣁⣴⣿⣿⣿⡇⠀⠀⣿⣿⣿⣿⠀")
        println("   ⠀⣿⣿⣿⣿⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⢸⣿⣿⣿⣿⠀")
        println("   ⠀⠛⠛⠛⠛⠀⠀⠘⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠛⠁⠀⠘⠛⠛⠛⠛⠀\u001B[0m")
    }

    fun asciiOrc() {
        println("\u001B[32m    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀  ⠀⠀⠀⠀⠀⠀⠀⠀⠀ ⢀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("  ⠀⠀⠀⠀⠀⠀⠀⠀⠀   ⠀⠀⠀⢠⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("    ⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣤⣶⣧⣄⣉⣉⣠⣼⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("    ⠀⠀⠀⠀⠀⠀⠀⢰⣿⣿⣿⣿⡿⣿⣿⣿⣿⢿⣿⣿⣿⣿⡆⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀⠀⠀⣼⣤⣤⣈⠙⠳⢄⣉⣋⡡⠞⠋⣁⣤⣤⣿⣧⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⢲⣶⣤⣄⡀⣿⣄⠙⠿⣿⣦⣤⡿⢿⣤⣴⣿⠿⠋⣠⣿⣿⢀⣠⣤⣶⡖⠀")
        println("   ⠀⠀⠙⣿⠛⠇⢸⣿⣿⡟⠀⡄⢉⠉⢀⡀⠉⡉⢠⠀⢻⣿⣿⡇⠸⠛⣿⠋⠀⠀")
        println("   ⠀⠀⠀⠘⣷⠀⢸⡏⠻⣿⣤⣤⠂⣠⣿⣿⣄⠑⣤⣤⣿⠟⢹⡇⠀⣾⠃⠀⠀⠀")
        println("  ⠀⠀⠀ ⠀⠘⢸⣿⡀⢀⠙⠻⢦⣌⣉⣉⣡⡴⠟⠋⡀⢀⣿⡇⣿⠃⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀⠀⢸⣿⣧⠈⠛⠂⠀⠉⠛⠛⠉⠀⠐⠛⠁⣼⣿⡇⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀⠀⠀⠸⣏⠀⣤⡶⠖⠛⠋⠉⠉⠙⠛⠲⢶⣤⠀⣹⠇⠀⠀⠀⠀⠀⠀")
        println("    ⠀⠀⠀⠀⠀⠀⠀⢹⣿⣿⣶⣿⣿⣿⣿⣿⣿⣿⣶⣿⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀")
        println("   ⠀⠀⠀⠀ ⠀⠀⠀⠀⠀⠈⠉⠉⠉⠛⠛⠛⠛⠉⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀\u001B[0m")

    }

    fun asciiDevilBoss() {
        println("\u001B[31m          (                      )")
        println("          |'    _,--------._    / |")
        println("          | `.,'            `. /  |")
        println("          `  '              ,-'   '")
        println("           '/_         _   (     /")
        println("          (,-.`.    ,',-.`. `__,'")
        println("           |'#' ),-','#'`= ,'.` |")
        println("           `._')  -'.'_,'   ) ))|")
        println("           /  (_.)'     .   -'//")
        println("          (  ________    ) )`'' ")
        println("           ' |V----V||  ' ,    ' ")
        println("            |`- -- -'   ,'   '  '      _____")
        println("     ___    |         .'    ' '  `._,-'     `-")
        println("        `.__,`---^---'       ' ` -'")
        println("           -.______  ' . /  ______,-")
        println("                   `.     ,'           \u001B[0m")
    }

    fun asciiCredits() {
        println("  ,ad8888ba,                                 88 88                               ")
        println(" d8''    `'8b                                88 ''   ,d                          ")
        println("d8'                                          88      88                          ")
        println("88            8b,dPPYba,  ,adPPYba,  ,adPPYb,88 88 MM88MMM ,adPPYba,  ,adPPYba,")
        println("88            88P'   'Y8 a8P_____88 a8'    `Y88 88   88   a8'     '8a I8[    ''  ")
        println("Y8,           88         8PP''''''' 8b       88 88   88   8b       d8  `'Y8ba,")
        println(" Y8a.    .a8P 88         '8b, , aa '8a,   ,d88  88   88,  '8a, , a8'  aa    ]8I ")
        println("  `'Y8888Y''  88          `'Ybbd8''  `''8bbdP'  88   ''Y8   'YbbdP'   ''YbbdP''")
        println("\n- Diseño del juego: Taratara")
        println("- Codigo del juego: Taratara")
        println("- Arte asciiart.eu y ascii.co.uk/art")
        println("- Beta testers: Guillem, Jan, Taratara")
    }

    fun asciiWin() {
        println("\u001B[32m8b        d8 ,ad8888ba,   88        88   I8,        8        ,8I  ,ad8888ba,   888b      88  ")
        println(" Y8,    ,8P d8''    `'8b  88        88   `8b       d8b       d8' d8''    `'8b  8888b     88  ")
        println("  Y8,  ,8P d8'        `8b 88        88    '8,     ,8'8,     ,8' d8'        `8b 88 `8b    88  ")
        println("   '8aa8'  88          88 88        88     Y8     8P Y8     8P  88          88 88  `8b   88  ")
        println("    `88'   88          88 88        88     `8b   d8' `8b   d8'  88          88 88   `8b  88  ")
        println("     88    Y8,        ,8P 88        88      `8a a8'   `8a a8'   Y8,        ,8P 88    `8b 88  ")
        println("     88     Y8a.    .a8P  Y8a.    .a8P       `8a8'     `8a8'     Y8a.    .a8P  88     `8888  ")
        println("     88      `'Y8888Y''    `'Y8888Y''         `8'       `8'       `'Y8888Y''   88      `888  \u001B[0m")
    }

    fun asciiLost() {
        println("\u001B[31m8b        d8 ,ad8888ba,   88        88    88          ,ad8888ba,    ad88888ba  888888888888")
        println(" Y8,    ,8P d8''    `'8b  88        88    88         d8'''    `'8b  d8''    '8b     88")
        println("  Y8,  ,8P d8'        `8b 88        88    88        d8'        `8b Y8,              88")
        println("   '8aa8'  88          88 88        88    88        88          88 `Y8aaaaa,        88")
        println("    `88'   88          88 88        88    88        88          88   `'''''8b,      88    ")
        println("     88    Y8,        ,8P 88        88    88        Y8,        ,8P         `8b      88       ")
        println("     88     Y8a.    .a8P  Y8a.    .a8P    88         Y8a.    .a8P  Y8a     a8P      88       ")
        println("     88      `'Y8888Y''    `'Y8888Y''     88888888888 `'Y8888Y''    'Y88888P'       88 \u001B[0m")
    }

    fun asciiGameOver() {
        println("                           ,--.")
        println("                          {    }")
        println("                          K,   }")
        println("                         /  `Y`")
        println("                    _   /   /")
        println("                   {_'-K.__/")
        println("                     `/-.__L._")
        println("                     /  ' /`\\_}")
        println("                    /  ' /     ")
        println("            ____   /  ' /")
        println("     ,-'~~~~    ~~/  ' /_")
        println("   ,'             ``~~~%%',")
        println("  (                     %  Y")
        println(" {                      %% I")
        println("{      -                 %  `.")
        println("|       ',                %  )")
        println("|        |   ,..__      __. Y")
        println("|    .,_./  Y ' / ^Y   J   )|")
        println("'           |' /   |   |   ||")
        println(" '          L_/    . _ (_,.'(")
        println("  ',   ,      ^^''' / |      )")
        println("    '_  '          /,L]     /")
        println("      '-_`-,       ` `   ./`")
        println("         `-(_            )")
        println("             ^^'..___,.--`")
        println("\n  ,ad8888ba, ")
        println(" d8'      `'''8b")
        println("d8'     ")
        println("88            ,adPPYYba, 88,dPYba,,adPYba,   ,adPPYba,     ,adPPYba,  8b       d8  ,adPPYba, 8b,dPPYba,")
        println("88      88888 ``     `Y8 88P'   '88'    '8a a8P_____88    a8'     '8a `8b     d8' a8P_____88 88P'   'Y8 ")
        println("Y8,        88 ,adPPPPP88 88      88      88 8PP```````    8b       d8  `8b   d8'  8PP``````` 88 ")
        println(" Y8a.    .a88 88,    ,88 88      88      88 '8b, , aa     '8a,   ,a8'   `8b,d8'   '8b,   ,aa 88")
        println("  `'Y88888P'  `'8bbdP'Y8 88      88      88  `'Ybbd8''     `'YbbdP''      '8'      `'Ybbd8'' 88")
    }
}